#!/usr/bin/env python3
"""Generate speech fixtures + dictations.json.

Usage: python3 test/gen_fixtures.py
Synthesizes each dictation with macOS `say` (skipped if the .m4a already
exists) and rewrites test/fixtures/dictations.json.
"""
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
FIXTURES = os.path.join(HERE, "fixtures")

AM1 = "Análisis Matemático 1"
AM2 = "Análisis Matemático 2"
F1 = "Física 1"
F2 = "Física 2"
EN = "English"

# (filename, subject, language, dictated text, mustMatch regexes)
ENTRIES = [
    # ---------- Análisis Matemático 1 ----------
    ("integral.m4a", AM1, "es",
     "integral de a a b de efe de equis de equis",
     ["\\\\int_a\\^b", "f\\(x\\)", "d\\s?x"]),
    ("sum.m4a", AM1, "es",
     "la sumatoria de i igual a uno hasta n de i al cuadrado",
     ["\\\\sum_\\{?i=1\\}?", "\\^\\{?n\\}?", "i\\^2"]),
    ("quadratic.m4a", AM1, "es",
     "x igual a menos b más o menos raíz cuadrada de b al cuadrado menos cuatro a c sobre dos a",
     ["\\\\frac", "\\\\sqrt", "\\\\pm", "b\\^2"]),
    ("am1-limit.m4a", AM1, "es",
     "el límite cuando equis tiende a cero de seno de equis sobre equis es igual a uno",
     ["\\\\lim", "x\\\\to ?0|x \\\\rightarrow ?0", "\\\\sin", "= ?1"]),
    ("am1-derivdef.m4a", AM1, "es",
     "la derivada de efe en equis es el límite cuando hache tiende a cero de efe de equis más hache menos efe de equis sobre hache",
     ["\\\\lim", "h ?\\\\to ?0|h ?\\\\rightarrow ?0", "f\\(x ?\\+ ?h\\) ?- ?f\\(x\\)"]),
    ("am1-taylor.m4a", AM1, "es",
     "la serie de taylor de e a la equis es la sumatoria de ene igual a cero hasta infinito de equis a la ene sobre ene factorial",
     ["\\\\sum_\\{?n ?= ?0\\}?", "\\^\\{?\\\\infty", "x\\^\\{?n", "n!"]),
    ("am1-lhopital.m4a", AM1, "es",
     "aplicamos la regla de l'hôpital al límite cuando equis tiende a cero de e a la equis menos uno sobre equis",
     ["\\\\lim", "e\\^\\{?x", "\\\\frac"]),
    ("am1-chain.m4a", AM1, "es",
     "la derivada de seno de equis al cuadrado es dos equis por coseno de equis al cuadrado",
     ["\\\\cos", "2 ?x", "x\\^2"]),
    ("am1-product.m4a", AM1, "es",
     "la derivada de un producto es efe prima por ge más efe por ge prima",
     ["f' ?g|f'\\\\cdot ?g|f'\\(x\\)", "f ?g'|f\\(x\\)"]),
    ("am1-quotient.m4a", AM1, "es",
     "la derivada de un cociente es efe prima ge menos efe ge prima sobre ge al cuadrado",
     ["\\\\frac", "g\\^2"]),
    ("am1-improper.m4a", AM1, "es",
     "la integral impropia de uno a infinito de uno sobre equis al cuadrado converge a uno",
     ["\\\\int_?\\{?1\\}?\\^?\\{?\\\\infty", "\\\\frac\\{1\\}"]),
    ("am1-parts.m4a", AM1, "es",
     "integramos por partes la integral de equis por e a la equis de equis",
     ["\\\\int", "x ?e\\^?\\{?x|xe\\^", "d\\s?x"]),
    ("am1-subst.m4a", AM1, "es",
     "por sustitución con u igual a equis al cuadrado",
     ["u ?= ?x\\^2"]),
    ("am1-continuity.m4a", AM1, "es",
     "efe es continua en a si el límite cuando equis tiende a a de efe de equis es igual a efe de a",
     ["\\\\lim", "f\\(a\\)"]),
    ("am1-mvt.m4a", AM1, "es",
     "el teorema del valor medio garantiza un ce donde efe prima de ce es efe de be menos efe de a sobre be menos a",
     ["f'\\(c\\)", "f\\(b\\) ?- ?f\\(a\\)"]),
    ("am1-euler.m4a", AM1, "es",
     "e a la i pi más uno es igual a cero",
     ["e\\^\\{?i ?\\\\pi|e\\^\\{i\\\\pi", "\\+ ?1 ?= ?0"]),
    ("am1-arctan.m4a", AM1, "es",
     "la derivada de arco tangente de equis es uno sobre uno más equis al cuadrado",
     ["\\\\arctan|arctan", "\\\\frac\\{1\\}\\{1 ?\\+ ?x\\^2\\}"]),
    ("am1-ln.m4a", AM1, "es",
     "la derivada de logaritmo natural de equis es uno sobre equis",
     ["\\\\ln|log", "\\\\frac\\{1\\}\\{x\\}"]),
    ("am1-exp-deriv.m4a", AM1, "es",
     "la derivada de e a la equis es e a la equis",
     ["e\\^\\{?x", "\\\\frac\\{d|derivada"]),
    ("am1-seq.m4a", AM1, "es",
     "la sucesión a ene tiende a ele si para todo épsilon existe un ene cero",
     ["a_n|a_\\{?n", "\\\\varepsilon|\\\\epsilon|épsilon", "n_0|N"]),
    ("am1-tangent.m4a", AM1, "es",
     "la recta tangente en el punto a es ye igual a efe de a más efe prima de a por equis menos a",
     ["f\\(a\\)", "f'\\(a\\)"]),
    ("am1-comp.m4a", AM1, "es",
     "la composición efe de ge de equis se escribe efe circulo ge",
     ["f ?\\\\circ ?g|f\\(g"]),
    ("am1-inf-limit.m4a", AM1, "es",
     "el límite cuando equis tiende a infinito de uno sobre equis es cero",
     ["\\\\infty", "\\\\frac\\{1\\}\\{x\\}|1/x", "= ?0"]),
    ("am1-bolzano.m4a", AM1, "es",
     "por el teorema de bolzano si efe de a y efe de be tienen signos opuestos existe una raíz en el intervalo",
     ["f\\(a\\)", "f\\(b\\)"]),

    # ---------- Análisis Matemático 2 ----------
    ("am2-doubleint.m4a", AM2, "es",
     "la integral doble sobre la región erre de efe de equis ye diferencial de equis diferencial de ye",
     ["\\\\iint|\\\\int ?\\\\int", "f\\(x ?, ?y\\)", "d\\s?[xy][^\\n]*d\\s?[xy]"]),
    ("am2-gradient.m4a", AM2, "es",
     "el gradiente de efe es parcial efe sobre parcial equis coma parcial efe sobre parcial ye",
     ["\\\\frac\\{\\\\partial", "\\\\partial ?x", "\\\\partial ?y"]),
    ("am2-ode.m4a", AM2, "es",
     "i griega prima más equis por i griega es igual a seno de equis",
     ["y'|y ?\\\\prime", "\\\\sin"]),
    ("am2-divergence.m4a", AM2, "es",
     "la divergencia del campo es parcial efe uno sobre parcial equis más parcial efe dos sobre parcial ye",
     ["\\\\nabla ?\\\\cdot|\\\\operatorname\\{div\\}|\\\\mathrm\\{div\\}|div", "\\\\partial"]),
    ("am2-curl.m4a", AM2, "es",
     "el rotacional de efe es nabla producto vectorial efe",
     ["\\\\nabla ?\\\\times"]),
    ("am2-laplacian.m4a", AM2, "es",
     "el laplaciano de efe es nabla al cuadrado de efe",
     ["\\\\nabla\\^2|\\\\Delta"]),
    ("am2-lagrange.m4a", AM2, "es",
     "con multiplicadores de lagrange nabla efe es lambda por nabla ge",
     ["\\\\lambda", "\\\\nabla|Lagrange"]),
    ("am2-polar.m4a", AM2, "es",
     "en coordenadas polares equis es erre coseno de tita y ye es erre seno de tita",
     ["r ?\\\\cos ?\\\\theta|r\\\\cos", "r ?\\\\sin ?\\\\theta|r\\\\sin"]),
    ("am2-triple.m4a", AM2, "es",
     "la integral triple sobre el volumen ve de la densidad de equis ye zeta",
     ["\\\\iiint|\\\\int ?\\\\int ?\\\\int", "d\\s?V|dV|d\\s?x"]),
    ("am2-line.m4a", AM2, "es",
     "la integral de línea del campo efe a lo largo de la curva ce",
     ["\\\\int_?\\{?C|\\\\oint", "d\\s?(\\\\mathbf\\{)?r|d\\s?l|d\\s?s"]),
    ("am2-green.m4a", AM2, "es",
     "el teorema de green convierte la integral de línea en una integral doble sobre la región",
     ["\\\\oint|\\\\iint|green", "\\\\iint|\\\\oint"]),
    ("am2-stokes.m4a", AM2, "es",
     "el teorema de stokes relaciona la circulación con la integral del rotacional sobre la superficie",
     ["\\\\oint|\\\\nabla ?\\\\times|rotacional|Stokes"]),
    ("am2-ode2.m4a", AM2, "es",
     "i griega segunda más omega al cuadrado i griega igual a cero tiene solución a seno de omega te más be coseno de omega te",
     ["y''|y ?\\\\prime\\\\prime", "\\\\omega", "\\\\sin|\\\\cos"]),
    ("am2-fourier.m4a", AM2, "es",
     "la serie de fourier de efe es a cero sobre dos más la sumatoria de a ene coseno de ene equis más be ene seno de ene equis",
     ["a_0|a_\\{?0", "\\\\sum", "\\\\cos", "\\\\sin"]),
    ("am2-laplace.m4a", AM2, "es",
     "la transformada de laplace de e a la a te es uno sobre ese menos a",
     ["\\\\mathcal\\{L\\}|L|laplace|Laplace", "\\\\frac\\{1\\}\\{s ?- ?a\\}|1/\\(s"]),
    ("am2-partial.m4a", AM2, "es",
     "la derivada parcial de equis al cuadrado por ye respecto de equis es dos equis ye",
     ["\\\\frac\\{\\\\partial|\\\\partial", "2 ?x ?y"]),
    ("am2-hessian.m4a", AM2, "es",
     "el hessiano es la matriz de segundas derivadas parciales de efe",
     ["\\\\partial\\^2|H|hessiana|Hessiana|hessian|Hessian"]),
    ("am2-saddle.m4a", AM2, "es",
     "un punto de silla tiene determinante del hessiano negativo",
     ["< ?0|det|H"]),
    ("am2-tangent-plane.m4a", AM2, "es",
     "el plano tangente a la superficie zeta igual efe de equis ye",
     ["z ?= ?f|z ?=|f\\(x ?, ?y\\)"]),
    ("am2-separable.m4a", AM2, "es",
     "la ecuación i griega prima igual equis por i griega es de variables separables",
     ["y'|y ?\\\\prime|dy|d\\s?y", "x ?y"]),
    ("am2-exact.m4a", AM2, "es",
     "una ecuación diferencial exacta satisface parcial eme sobre parcial ye igual parcial ene sobre parcial equis",
     ["\\\\frac\\{\\\\partial ?M|\\\\partial ?M|exacta", "\\\\partial"]),

    # ---------- Física 1 ----------
    ("f1-newton.m4a", F1, "es",
     "la segunda ley de newton dice que efe es igual a eme por a",
     ["F ?= ?m ?\\\\cdot ?a|F ?= ?m ?a|F ?= ?ma"]),
    ("f1-velocity.m4a", F1, "es",
     "la velocidad es la derivada de la posición equis respecto del tiempo te",
     ["v ?=|\\\\dot ?x", "\\\\frac\\{d|\\\\dot", "d\\s?t|dt"]),
    ("f1-kinetic.m4a", F1, "es",
     "la energía cinética es un medio de eme por ve al cuadrado",
     ["\\\\frac\\{1\\}\\{2\\}|\\\\tfrac\\{1\\}\\{2\\}|1/2|\\\\frac12", "m ?v\\^2|mv\\^\\{?2"]),
    ("f1-harmonic.m4a", F1, "es",
     "equis de te es igual a a por coseno de omega te más fi",
     ["x\\(t\\)", "\\\\cos", "\\\\omega", "\\\\phi|\\\\varphi"]),
    ("f1-mruv.m4a", F1, "es",
     "en el mruv la posición es equis cero más ve cero te más un medio de a te al cuadrado",
     ["x_0|x_\\{?0", "v_0 ?t|v_\\{?0", "\\\\frac\\{1\\}\\{2\\} ?a ?t\\^2|at\\^2|a ?t\\^\\{?2"]),
    ("f1-freefall.m4a", F1, "es",
     "en caída libre la aceleración es ge igual a nueve coma ocho metros por segundo al cuadrado",
     ["g", "9\\{?,\\}?8|9[.,]8"]),
    ("f1-projectile.m4a", F1, "es",
     "en el tiro parabólico la componente horizontal es ve coseno de tita y la vertical es ve seno de tita",
     ["v ?\\\\cos ?\\\\theta|v\\\\cos", "v ?\\\\sin ?\\\\theta|v\\\\sin"]),
    ("f1-friction.m4a", F1, "es",
     "la fuerza de rozamiento es mu por la normal",
     ["\\\\mu", "N|f_r|rozamiento"]),
    ("f1-newton1.m4a", F1, "es",
     "la primera ley de newton dice que si la fuerza neta es cero la velocidad es constante",
     ["F", "v"]),
    ("f1-newton3.m4a", F1, "es",
     "la tercera ley de newton dice que efe uno dos es menos efe dos uno",
     ["F_\\{?12|F_12", "F_\\{?21|F_21"]),
    ("f1-work.m4a", F1, "es",
     "el trabajo es efe por de por coseno de tita",
     ["W ?= ?F|W", "\\\\cos ?\\\\theta|\\\\cos"]),
    ("f1-potential.m4a", F1, "es",
     "la energía potencial gravitatoria es eme ge hache",
     ["m ?g ?h|mgh"]),
    ("f1-conserve.m4a", F1, "es",
     "por conservación de la energía eme ge hache es un medio de eme ve al cuadrado",
     ["m ?g ?h|mgh", "\\\\frac\\{1\\}\\{2\\}|1/2", "v\\^2"]),
    ("f1-power.m4a", F1, "es",
     "la potencia es el trabajo sobre el tiempo",
     ["P ?= ?\\\\frac\\{W\\}\\{t\\}|P ?= ?W/t|P"]),
    ("f1-momentum.m4a", F1, "es",
     "el momento lineal es eme por ve",
     ["p ?= ?m ?v|mv"]),
    ("f1-impulse.m4a", F1, "es",
     "el impulso es la variación del momento lineal",
     ["J ?= ?\\\\Delta ?p|I ?= ?\\\\Delta ?p|\\\\Delta ?p"]),
    ("f1-torque.m4a", F1, "es",
     "el torque es el producto vectorial de erre por efe",
     ["\\\\tau", "\\\\times|\\\\vec\\{r\\}|r ?\\\\times"]),
    ("f1-inertia.m4a", F1, "es",
     "el momento de inercia de un disco es un medio de eme erre al cuadrado",
     ["I ?= ?\\\\frac\\{1\\}\\{2\\} ?M ?R\\^2|\\\\frac\\{1\\}\\{2\\}|MR"]),
    ("f1-angular.m4a", F1, "es",
     "el momento angular es ele igual erre vectorial pe",
     ["L ?=|r ?\\\\times ?p|\\\\vec\\{r\\}"]),
    ("f1-gravity.m4a", F1, "es",
     "la ley de gravitación universal es efe igual ge eme uno eme dos sobre erre al cuadrado",
     ["G", "\\\\frac\\{?m_1 ?m_2\\}?\\{?r\\^2|m_1|m 1"]),
    ("f1-pendulum.m4a", F1, "es",
     "el período del péndulo es dos pi raíz de ele sobre ge",
     ["2\\\\pi|2 ?\\\\pi", "\\\\sqrt", "l|L"]),
    ("f1-centripetal.m4a", F1, "es",
     "la aceleración centrípeta es ve al cuadrado sobre erre",
     ["\\\\frac\\{v\\^2\\}\\{r\\}|v\\^2/r|v\\^2"]),
    ("f1-omega.m4a", F1, "es",
     "la velocidad angular es dos pi por la frecuencia",
     ["\\\\omega ?= ?2 ?\\\\pi ?f|2\\\\pi ?f"]),
    ("f1-hooke.m4a", F1, "es",
     "la ley de hooke es efe igual menos ka por equis",
     ["F ?= ?- ?k ?x|- ?k ?x|-kx"]),

    # ---------- Física 2 ----------
    ("f2-gauss.m4a", F2, "es",
     "la ley de gauss dice que la integral de superficie cerrada del campo eléctrico es igual a la carga encerrada sobre épsilon cero",
     ["\\\\oint|\\\\Phi|\\\\oiint", "\\\\(varepsilon|epsilon)_0|epsilon_0", "Q|q"]),
    ("f2-wave.m4a", F2, "es",
     "la ecuación de onda es parcial al cuadrado de ye sobre parcial equis al cuadrado igual a uno sobre ve al cuadrado por parcial al cuadrado de ye sobre parcial te al cuadrado",
     ["\\\\partial\\^2|\\\\partial ?\\^?2", "v\\^2", "\\\\partial ?t"]),
    ("f2-coulomb.m4a", F2, "es",
     "la ley de coulomb es efe igual ka cu uno cu dos sobre erre al cuadrado",
     ["k", "q_1 ?q_2|q_\\{?1|q 1", "r\\^2"]),
    ("f2-efield.m4a", F2, "es",
     "el campo eléctrico es la fuerza sobre la carga de prueba",
     ["E ?= ?\\\\frac\\{F\\}\\{q\\}|E ?= ?F/q|E"]),
    ("f2-epotential.m4a", F2, "es",
     "la diferencia de potencial es menos la integral del campo eléctrico por de ele",
     ["V|U", "\\\\int", "E"]),
    ("f2-capacitor.m4a", F2, "es",
     "la capacidad es cu sobre ve",
     ["C ?= ?\\\\frac\\{Q\\}\\{V\\}|C ?= ?Q/V|C"]),
    ("f2-energy-cap.m4a", F2, "es",
     "la energía del capacitor es un medio de cu por ve al cuadrado",
     ["\\\\frac\\{1\\}\\{2\\}|1/2", "V\\^2|Q|C"]),
    ("f2-ohm.m4a", F2, "es",
     "la ley de ohm es ve igual i por erre",
     ["V ?= ?I ?\\\\cdot ?R|V ?= ?I ?\\\\times ?R|V ?= ?I ?R|IR"]),
    ("f2-resistance.m4a", F2, "es",
     "la resistencia es ro por ele sobre a",
     ["R ?= ?\\\\rho|\\\\rho", "[lL]/A|\\\\frac\\{\\\\rho ?[lL]\\}\\{A\\}"]),
    ("f2-kirchhoff.m4a", F2, "es",
     "la ley de nodos de kirchhoff dice que la suma de corrientes es cero",
     ["\\\\sum", "I", "0|cero"]),
    ("f2-lorentz.m4a", F2, "es",
     "la fuerza de lorentz es cu por ve vectorial be",
     ["F ?=|q", "\\\\times|\\\\vec\\{v\\}|v"]),
    ("f2-ampere.m4a", F2, "es",
     "la ley de ampere dice que la circulación del campo magnético es mu cero por la corriente encerrada",
     ["\\\\oint|\\\\mu_0|mu", "I"]),
    ("f2-faraday.m4a", F2, "es",
     "la ley de faraday dice que la fem es menos la derivada del flujo magnético",
     ["\\\\mathcal\\{E\\}|fem|EMF|\\\\varepsilon", "\\\\Phi|flujo", "-"]),
    ("f2-flux.m4a", F2, "es",
     "el flujo magnético es la integral de be por de a",
     ["\\\\Phi|Phi", "\\\\int", "B"]),
    ("f2-inductor.m4a", F2, "es",
     "la energía del inductor es un medio de ele por i al cuadrado",
     ["\\\\frac\\{1\\}\\{2\\}|1/2", "L ?I\\^2|LI"]),
    ("f2-displacement.m4a", F2, "es",
     "maxwell agregó la corriente de desplazamiento épsilon cero por la derivada del flujo eléctrico",
     ["\\\\epsilon_0|\\\\varepsilon_0|epsilon", "\\\\Phi|flujo|\\\\frac"]),
    ("f2-emwave.m4a", F2, "es",
     "la velocidad de la luz es uno sobre raíz de épsilon cero mu cero",
     ["c ?= ?\\\\frac\\{1\\}|c ?=", "\\\\sqrt", "\\\\mu_0|mu"]),
    ("f2-snell.m4a", F2, "es",
     "la ley de snell es ene uno seno de tita uno igual ene dos seno de tita dos",
     ["n_1|n_\\{?1", "\\\\sin", "n_2|n_\\{?2"]),
    ("f2-interference.m4a", F2, "es",
     "la interferencia constructiva ocurre cuando la diferencia de camino es un múltiplo entero de lambda",
     ["\\\\Delta|d", "\\\\lambda", "m|n"]),
    ("f2-doppler.m4a", F2, "es",
     "el efecto doppler da una frecuencia efe prima igual efe por ve más ve cero sobre ve",
     ["f'|f ?\\\\prime|f'", "\\\\frac", "v"]),
    ("f2-heat.m4a", F2, "es",
     "el calor es eme por ce por delta te",
     ["Q ?= ?m ?c|mc", "\\\\Delta ?[Tt]|delta"]),
    ("f2-ideal.m4a", F2, "es",
     "la ley de gases ideales es pe ve igual ene erre te",
     ["P ?V ?= ?n ?R ?T|PV ?= ?nRT|PV"]),
    ("f2-entropy.m4a", F2, "es",
     "la variación de entropía es delta ese igual de cu sobre te",
     ["\\\\Delta ?S", "\\\\frac|dQ|Q"]),
    ("f2-firstlaw.m4a", F2, "es",
     "la primera ley de la termodinámica es delta u igual cu menos doble ve",
     ["\\\\Delta ?U ?= ?Q ?- ?W|\\\\Delta ?U|Delta U"]),

    # ---------- English ----------
    ("en-integral.m4a", EN, "en",
     "the integral from a to b of f of x d x",
     ["\\\\int_a\\^b", "f\\(x\\)", "d\\s?x"]),
    ("en-sum.m4a", EN, "en",
     "the sum from i equals one to n of i squared",
     ["\\\\sum_\\{i=1\\}", "\\^\\{?n\\}?", "i\\^2"]),
]


def main() -> None:
    os.makedirs(FIXTURES, exist_ok=True)
    made = 0
    for filename, _subject, lang, dictated, _mm in ENTRIES:
        path = os.path.join(FIXTURES, filename)
        if os.path.exists(path):
            continue
        voice = "Monica" if lang == "es" else "Samantha"
        subprocess.run(["say", "-v", voice, "-o", path, dictated], check=True)
        made += 1
        print(f"  generated {filename}", flush=True)

    data = [
        {
            "file": f,
            "subject": s,
            "language": lang,
            "dictated": d,
            "mustMatch": mm,
        }
        for f, s, lang, d, mm in ENTRIES
    ]
    with open(os.path.join(FIXTURES, "dictations.json"), "w") as fh:
        json.dump(data, fh, indent="\t", ensure_ascii=False)
        fh.write("\n")
    print(f"{len(data)} dictations ({made} new audio files)")


if __name__ == "__main__":
    sys.exit(main())
